language: php
sudo: false

cache:
  - composer

matrix:
  fast_finish: true

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

install:
  - if [[ "$TRAVIS_PHP_VERSION" == '5.6' ]]; then composer require satooshi/php-coveralls:dev-master -n ; fi
  - composer install -n

script:
  - if [[ "$TRAVIS_PHP_VERSION" == '5.6' ]]; then composer run-script test-ci ; fi
  - composer run-script test-ci

after_script:
  - if [[ "$TRAVIS_PHP_VERSION" == '5.6' ]]; then php vendor/bin/coveralls -v ; fi
